### PR TITLE
Fix for `--use_cuda False` in eval_knn.py

### PR DESCRIPTION
**Pull request by mgpadalkar**
Fix for `--use_cuda False` in eval_knn.py: https://github.com/facebookresearch/dino/issues/135.

### CODE REVIEW

**Comment by mathildecaron31** [comment]
Hi @mgpadalkar 
Can you squash your 6 commits into a single one please ?

**Comment by mgpadalkar** [comment]
Hi @mathildecaron31,
Sure, I wish to....let me figure out how to do it.

**Comment by mgpadalkar** [comment]
Hi @mathildecaron31, somehow I am now able to squash them into one. I can create a fresh fork (deleting the current one) and then send a PR. Sorry for the trouble...any other suggestions?

**Comment by woctezuma** [comment]
Just for info, and maybe you already know all that, but ideally, you would have:
- created a branch on your fork,
- pulled the latest version of `main` from the source,
- **rebased** your fork on the updated `main`.

Since you worked directly on the `main` branch instead, you had to do what you did with the fresh fork.

**Comment by mgpadalkar** [comment]
Thanks @woctezuma!
This was my first PR and I honestly didn't know the proper procedure. :innocent:
I will keep this is mind for future PRs. :smiley: :thumbsup:

**Pull request closed without merging**
